#create table device_company(dev_id varchar(10),company varchar(10),primary key(dev_id));
#desc device_company;
#create table users(username varchar(20),password varchar(256),primary key(username));
#create table devices(dev_id varchar(10),username varchar(20),foreign key(dev_id) references device_company(dev_id))
#desc devices;
#insert into device_company values("A1","comp A");
#insert into device_company values("B1","comp B");
#select * from device_company;
#create table device_cert(dev_id varchar(10),cert blob,foreign key(dev_id) references device_company(dev_id));
select * from device_cert;
show databases;
commit;
SELECT user, host FROM mysql.user WHERE user = 'root';
create table company(cname varchar(10),url varchar(100));
drop table company;
insert into company values('comp A','localhost:9020');
insert into company values('comp B','localhost:9021');
desc company;
select * from device_company;
insert into company values("comp A","localhost:9020");
insert into company values("comp B","localhost:9021");
create table blockchain_wallet(walletname varchar(20),walletpword varchar(200),username varchar(20),company varchar(10),foreign key(username) references users(username));
select * from users;
insert into blockchain_wallet values('default','PW5JsywcowQF74onks9WMemv18MZsF7zTY415i1V8YQxRxXiwsDAu','alice3','comp A');
select * from blockchain_wallet;
delete from blockchain_wallet where username='alice2';
drop table blockchain_wallet;
SELECT url FROM company where cname in (SELECT company FROM device_company WHERE dev_id='A1');
create table trans(trans_id int AUTO_INCREMENT primary key,dev_id varchar(10),tid varchar(10),seeking varchar(20),price varchar(10),tme timestamp,authtoken varchar(200));
desc trans;
drop table trans;
create table tmp(a varchar(10),t timestamp);
insert into tmp values(null,'2020-05-14 17:54:24.959535');
select * from tmp where t is not null order by t desc;
delete from tmp where a is null and t is not null;
update tmp set a='b' where a is null;
create table tmp2(id int AUTO_INCREMENT primary key,a varchar(10));
insert into tmp2 values(null,'a');
select * from tmp2;
show tables;
desc users;
select * from trans;# where tme='2020-05-15 01:23:37';
update trans set authtoken=null where trans_id=1;
delete from trans where authtoken=null;
create table tmp_auth(username varchar(20),password varchar(256));
select walletname,walletpword from blockchain_wallet where username in (select username from users where username='eosio' and password='efbb5450f4528e0dd33ff1873f52a175e8f280eb591c6725a1227b9aec8eac0e');
select * from users;
select * from tmp where t>'2020-05-14 17:44:37';